# Generated by Django 4.2.7 on 2026-08-02 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasazProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('estimated_count', models.PositiveIntegerField(blank=True, null=True)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('step1_complete', 'Step 1 Complete'), ('step2_complete', 'Step 2 Complete'), ('processing', 'Processing'), ('completed', 'Completed')], default='draft', max_length=30)),
                ('step2_definition', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasaz_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datasaz Project',
                'verbose_name_plural': 'Datasaz Projects',
                'db_table': 'datasaz_projects',
                'ordering': ['-updated_at'],
            },
        ),
    ]
